export const DEFAULT_SCALING_HOUR = 4;
export const DEFAULT_LINE_WIDTH_SCALING_HOUR = 25;

export const DEFAULT_SCALING_MINUTE = 7;
export const DEFAULT_LINE_WIDTH_SCALING_MINUTE = 32;

export const DEFAULT_SCALING_SECOND = 16;
export const DEFAULT_LINE_WIDTH_SCALING_SECONDS = 42;

export const DEFAULT_CENTER_SCALING = 42;

export const UNITS_PER_ROTATION_SECOND = 1000;
export const UNITS_PER_ROTATION_MINUTE = 60;

export const HOURS_PER_ROTATION = 12;
export const MINUTES_PER_ROTATION = 60;
export const SECONDS_PER_ROTATION = 60;
export const MILLIS_PER_ROTATION = 1000;

export const DEFAULT_NUMBERS_LINEWIDTH = 1.5;

export const DEFAULT_NUMBERS_FILL = '#fff';
export const DEFAULT_NUMBERS_STROKE = '#000';

export const ACTIVE_NUMBERS_FILL = '#66b3ff';
export const ACTIVE_NUMBERS_STROKE = '#fff';
